### Week 10 - Home work

# Instructions
You need to finish all the sections and the points mentioned in each section.

# Section-1 
You need to finish all the given points in a given section:

       Update/Upgrade the NumPy package to the latest version
       Install/Upgrade another package (e.g. Pandas)
       Import NumPy as np
       Use the np.array() function to create an array variable - array_1
       E.g:
        array([[ 10,  15],
               [ 17, 100]])   
   


In [1]:
import numpy as np
np_1SD = np.array([100,110,120,130, 140])
np_1SD

array([100, 110, 120, 130, 140])

In [2]:
np_2SD = np.array([[200,300,400,500,600], [430,540,650,760,870], [110,220,330,440,550]])
np_2SD

array([[200, 300, 400, 500, 600],
       [430, 540, 650, 760, 870],
       [110, 220, 330, 440, 550]])

In [3]:
np_3SD = np.array([[[100,200,300,400,500], [110,210,310,401,510]], [[110,120,130,140,150], [510,520,530,540,500]]])
np_3SD

array([[[100, 200, 300, 400, 500],
        [110, 210, 310, 401, 510]],

       [[110, 120, 130, 140, 150],
        [510, 520, 530, 540, 500]]])

# Section-2
    * Generate 4 arrays of size 8
     * 1st Array empty "empty"
     * 2nd array full of  0s
     * 3rd array full of 1s
     * Last array full of 2s
    * Generate 4 more arrays. This time, they should be 2 by 4 arrays.
        * An empty array with the same shape as np_1SD. 
        * An 2-D array of 0s with the same shape as array_2D.
        * A 3-D array of 1s with the same shappe as array_3D.
        * A 3-D array of 2s with the same shape as array_3D.

In [14]:
arr1 = np.empty(8)
arr2 = np.zeros(8, dtype=int)
arr3 = np.ones(8, dtype=int)
arr4 = np.full(8, 2, dtype=int)
print(arr1)
print(arr2)
print(arr3)
print(arr4)

arr5 = np.empty((2, 4))
arr6 = np.zeros((2, 4))
arr7 = np.ones((2, 4))
arr8 = np.full((2, 4), 2)
print(arr5)
print(arr6)
print(arr7)
print(arr8)

[1. 1. 1. 1. 1. 1. 1. 1.]
[0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1]
[2 2 2 2 2 2 2 2]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2 2 2 2]
 [2 2 2 2]]


# Section -3 
#### Using np.arange() function, solve following
      Generate array from 0 to 40, excluding 40. 
      Generate Array 0 to 40, including 40. 
      Generate integers from 35 to 50, including 50. 
      Generate where 5-th integers from 35 to 50, including 50. 


In [22]:
arr1 = np.array(range(0, 40))
print(arr1)
arr1 = np.array(range(0, 41))
print(arr1)
arr1 = np.array(range(35, 51))
print(arr1)
arr1 = np.array(range(35, 51, 5))
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
[35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[35 40 45 50]


# Section 4
Generate the random value using numpy functions such as .random()

    Use the probability to generate the single event
    Array size of 8 with the probabilities of 8 events. 
    Array of 4 by 8 2 dimensional array with the probabilities of 40 events.  

In [24]:
np.set_printoptions(suppress=True, linewidth=150)
events = [f"E{i+1}" for i in range(40)]
probs = np.full(40, 1/40)
array_4x8 = np.random.choice(events, size=(4, 8), p=probs)
print(array_4x8)


[['E31' 'E27' 'E28' 'E3' 'E17' 'E2' 'E25' 'E40']
 ['E19' 'E26' 'E5' 'E40' 'E38' 'E11' 'E26' 'E3']
 ['E27' 'E31' 'E23' 'E27' 'E6' 'E20' 'E27' 'E3']
 ['E33' 'E39' 'E21' 'E28' 'E11' 'E5' 'E16' 'E9']]


# Section 5
    Import the file and display it contents. You can use loadtxt(). You can use the file creditor-total-price.csv
    Import the file and display it contents. You can use np.genfromtxt(). You can use the file creditor-total-price.csv
        Set the data type to strings. 
        Skip the first row of the dataset. 
        Skip the last 15 rows of the dataset. 
        Only pull data from the 2nd, 3rd and 5th columns. 


Hint: By default np.loadtxt() asusmes all the values will be numeric, so it crashes when it encounters text data. We can bypass this by specifying the datatype to NumPy strings when importing.

In [41]:
import os
print(os.getcwd())
data = np.loadtxt("E:\\Masters Data Analytics\\MSDA-class-work\\DATA-200\\creditors-LT.csv", delimiter=',', skiprows=1)

E:\Masters Data Analytics\MSDA-class-work\DATA-200


ValueError: could not convert string 'uid_1' to float64 at row 0, column 2.

# Section 6 
    Slice the first column of the np_2SD array
    array([200, 430, 110])
    Slice the last column of the np_2SD  array
    array([600, 870, 550])
    Slice the second row of the np_2SD array
    array([430, 540, 650, 760, 870])
    Slice the last two columns of the np_2SD row of the np_2SD array
    array([760, 870])
    Slice the 2-nd row of the np_2SD array excluding the last two columns
    array([430, 540, 650])
    Slice everything excluding the first row and last column of the np_2SD array
    array([[430, 540, 650, 760],
           [110, 220, 330, 440]])
    Slice the 1st, 3rd and 5th columns of the np_3SD array
    array([[ 1, 11],
           [11, 51]])
    Slice every other column of both matrices in the np_3SD array
    array([[[ 10,  30,  50],
            [110, 310, 510]],
    
           [[110, 130, 150],
            [510, 530,  50]]])
    Use conditional slicing to check if the individual elements of each array satisfy a given condition on np_1SD(e.g. greater than 8)
    array([False,  True,  True,  True,  True])
    Add a second condition and disaply which individual elements satisfy both np_1SD , np_2SD and np_3SD (e.g. greater than 10 and odd)

